### ISSUE TITLE
[Nuxt3] getSync2 is not a function

### ISSUE THREAD

**Issue by DJafari** [permafrost-dev/node-ray#190]
```javascript
import { ray } from 'node-ray/web'
ray('something')
```

```
getSync2 is not a function

at Proxy.getOriginData (./node_modules/node-ray/dist/web.esm.mjs:2220:24)
at ./node_modules/node-ray/dist/web.esm.mjs:2258:34
at Array.forEach ()
at Proxy.sendRequest (./node_modules/node-ray/dist/web.esm.mjs:2257:14)
at Proxy.send (./node_modules/node-ray/dist/web.esm.mjs:2128:17)
at __vite_ssr_import_0__.watch.immediate (./composables/useRay.ts:10:43)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
at callWithAsyncErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:164:17)
at doWatch (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1726:7)
```

**Comment by slavarazum** [comment]
Hi @DJafari.
How did you solve it?

**Comment by DJafari** [comment]
@slavarazum 
you must call ray in client side only, you can disable ssr to check this

**Comment by slavarazum** [comment]
In my case I use node version `node-ray`.
Trying to run in testing environment.

**Comment by DJafari** [comment]
@slavarazum so i think you must open new issue
